### ISSUE TITLE
Fix puppetboard key issues

### ISSUE THREAD

**Issue by mattock** [Puppet-Finland/puppet-puppetmaster#14]
Puppet-lint reports a couple of problems:
```
./puppetboard.pp - WARNING: top-scope variable being used without an explicit namespace on line 42
./puppetboard.pp - WARNING: top-scope variable being used without an explicit namespace on line 44
```
The lines in question are:
```
$puppetboard_puppetdb_key  = "${::settings::ssldir}/private_keys/${puppetboard_certname}.pem"
$puppetboard_puppetdb_cert = "${::settings::ssldir}/certs/${puppetboard_certname}.pem"
```
The variable $puppetboard_certname is not defined.

**Comment by kibahop** [comment]
Why not just reference the key and the cert in /etc/puppetlabs/puppetdb/ssl, where puppetdb class puts them, if ssl_deploy_certs is true.

**Comment by mattock** [comment]
I tested this with Vagrant using puppetserver-xenial VM. Puppetboard came right up with SSL at https://<span></span>192.168.221.201/puppetboard.
