### ISSUE TITLE
Installer fails once puppetserver is in production use

### ISSUE THREAD

**Issue by mattock** [Puppet-Finland/puppet-puppetmaster#19]
This happens because Puppet defaults to using standard location (/etc/puppetlabs) for Hiera. This can and should be overridden in installer configuration.

**Comment by kibahop** [comment]
Tested with Centos 7 with control repo stuff in place. No problems were observable.

**Comment by mattock** [comment]
The problem only occurs if the node has a matching yaml file in the production environment. This was verified by @kibahop. I [asked](https://community.theforeman.org/t/custom-kafo-based-puppetmaster-installer-fails-if-puppetmaster-has-a-yaml-flie-in-production-environment/10496) about this on Foreman forums.
